//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAkhir.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahKaryawan", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahKaryawan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JenisKelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeKaryawanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaKaryawanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoHpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alamat {
            get {
                return this.AlamatField;
            }
            set {
                if ((object.ReferenceEquals(this.AlamatField, value) != true)) {
                    this.AlamatField = value;
                    this.RaisePropertyChanged("Alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JenisKelamin {
            get {
                return this.JenisKelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.JenisKelaminField, value) != true)) {
                    this.JenisKelaminField = value;
                    this.RaisePropertyChanged("JenisKelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeKaryawan {
            get {
                return this.KodeKaryawanField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeKaryawanField, value) != true)) {
                    this.KodeKaryawanField = value;
                    this.RaisePropertyChanged("KodeKaryawan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaKaryawan {
            get {
                return this.NamaKaryawanField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaKaryawanField, value) != true)) {
                    this.NamaKaryawanField = value;
                    this.RaisePropertyChanged("NamaKaryawan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoHp {
            get {
                return this.NoHpField;
            }
            set {
                if ((object.ReferenceEquals(this.NoHpField, value) != true)) {
                    this.NoHpField = value;
                    this.RaisePropertyChanged("NoHp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahApoteker", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahApoteker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JenisKelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeApotekerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaApotekerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoHpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alamat {
            get {
                return this.AlamatField;
            }
            set {
                if ((object.ReferenceEquals(this.AlamatField, value) != true)) {
                    this.AlamatField = value;
                    this.RaisePropertyChanged("Alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JenisKelamin {
            get {
                return this.JenisKelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.JenisKelaminField, value) != true)) {
                    this.JenisKelaminField = value;
                    this.RaisePropertyChanged("JenisKelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeApoteker {
            get {
                return this.KodeApotekerField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeApotekerField, value) != true)) {
                    this.KodeApotekerField = value;
                    this.RaisePropertyChanged("KodeApoteker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaApoteker {
            get {
                return this.NamaApotekerField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaApotekerField, value) != true)) {
                    this.NamaApotekerField = value;
                    this.RaisePropertyChanged("NamaApoteker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoHp {
            get {
                return this.NoHpField;
            }
            set {
                if ((object.ReferenceEquals(this.NoHpField, value) != true)) {
                    this.NoHpField = value;
                    this.RaisePropertyChanged("NoHp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahDokter", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahDokter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JenisKelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoHpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alamat {
            get {
                return this.AlamatField;
            }
            set {
                if ((object.ReferenceEquals(this.AlamatField, value) != true)) {
                    this.AlamatField = value;
                    this.RaisePropertyChanged("Alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JenisKelamin {
            get {
                return this.JenisKelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.JenisKelaminField, value) != true)) {
                    this.JenisKelaminField = value;
                    this.RaisePropertyChanged("JenisKelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeDokter {
            get {
                return this.KodeDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeDokterField, value) != true)) {
                    this.KodeDokterField = value;
                    this.RaisePropertyChanged("KodeDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaDokter {
            get {
                return this.NamaDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaDokterField, value) != true)) {
                    this.NamaDokterField = value;
                    this.RaisePropertyChanged("NamaDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoHp {
            get {
                return this.NoHpField;
            }
            set {
                if ((object.ReferenceEquals(this.NoHpField, value) != true)) {
                    this.NoHpField = value;
                    this.RaisePropertyChanged("NoHp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahPerawat", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahPerawat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JenisKelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodePerawatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaPerawatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoHpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alamat {
            get {
                return this.AlamatField;
            }
            set {
                if ((object.ReferenceEquals(this.AlamatField, value) != true)) {
                    this.AlamatField = value;
                    this.RaisePropertyChanged("Alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JenisKelamin {
            get {
                return this.JenisKelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.JenisKelaminField, value) != true)) {
                    this.JenisKelaminField = value;
                    this.RaisePropertyChanged("JenisKelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodePerawat {
            get {
                return this.KodePerawatField;
            }
            set {
                if ((object.ReferenceEquals(this.KodePerawatField, value) != true)) {
                    this.KodePerawatField = value;
                    this.RaisePropertyChanged("KodePerawat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaPerawat {
            get {
                return this.NamaPerawatField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaPerawatField, value) != true)) {
                    this.NamaPerawatField = value;
                    this.RaisePropertyChanged("NamaPerawat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoHp {
            get {
                return this.NoHpField;
            }
            set {
                if ((object.ReferenceEquals(this.NoHpField, value) != true)) {
                    this.NoHpField = value;
                    this.RaisePropertyChanged("NoHp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahPasien", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahPasien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JenisKelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodePasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UmurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alamat {
            get {
                return this.AlamatField;
            }
            set {
                if ((object.ReferenceEquals(this.AlamatField, value) != true)) {
                    this.AlamatField = value;
                    this.RaisePropertyChanged("Alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JenisKelamin {
            get {
                return this.JenisKelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.JenisKelaminField, value) != true)) {
                    this.JenisKelaminField = value;
                    this.RaisePropertyChanged("JenisKelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodePasien {
            get {
                return this.KodePasienField;
            }
            set {
                if ((object.ReferenceEquals(this.KodePasienField, value) != true)) {
                    this.KodePasienField = value;
                    this.RaisePropertyChanged("KodePasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaPasien {
            get {
                return this.NamaPasienField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaPasienField, value) != true)) {
                    this.NamaPasienField = value;
                    this.RaisePropertyChanged("NamaPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Umur {
            get {
                return this.UmurField;
            }
            set {
                if ((object.ReferenceEquals(this.UmurField, value) != true)) {
                    this.UmurField = value;
                    this.RaisePropertyChanged("Umur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahRI", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahRI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BiayaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeObatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodePasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodePerawatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeRIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeRuanganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaObatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaPerawatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaRuanganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TglKeluarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TglMasukField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Biaya {
            get {
                return this.BiayaField;
            }
            set {
                if ((object.ReferenceEquals(this.BiayaField, value) != true)) {
                    this.BiayaField = value;
                    this.RaisePropertyChanged("Biaya");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeDokter {
            get {
                return this.KodeDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeDokterField, value) != true)) {
                    this.KodeDokterField = value;
                    this.RaisePropertyChanged("KodeDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeObat {
            get {
                return this.KodeObatField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeObatField, value) != true)) {
                    this.KodeObatField = value;
                    this.RaisePropertyChanged("KodeObat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodePasien {
            get {
                return this.KodePasienField;
            }
            set {
                if ((object.ReferenceEquals(this.KodePasienField, value) != true)) {
                    this.KodePasienField = value;
                    this.RaisePropertyChanged("KodePasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodePerawat {
            get {
                return this.KodePerawatField;
            }
            set {
                if ((object.ReferenceEquals(this.KodePerawatField, value) != true)) {
                    this.KodePerawatField = value;
                    this.RaisePropertyChanged("KodePerawat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeRI {
            get {
                return this.KodeRIField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeRIField, value) != true)) {
                    this.KodeRIField = value;
                    this.RaisePropertyChanged("KodeRI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeRuangan {
            get {
                return this.KodeRuanganField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeRuanganField, value) != true)) {
                    this.KodeRuanganField = value;
                    this.RaisePropertyChanged("KodeRuangan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaDokter {
            get {
                return this.NamaDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaDokterField, value) != true)) {
                    this.NamaDokterField = value;
                    this.RaisePropertyChanged("NamaDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaObat {
            get {
                return this.NamaObatField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaObatField, value) != true)) {
                    this.NamaObatField = value;
                    this.RaisePropertyChanged("NamaObat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaPasien {
            get {
                return this.NamaPasienField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaPasienField, value) != true)) {
                    this.NamaPasienField = value;
                    this.RaisePropertyChanged("NamaPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaPerawat {
            get {
                return this.NamaPerawatField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaPerawatField, value) != true)) {
                    this.NamaPerawatField = value;
                    this.RaisePropertyChanged("NamaPerawat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaRuangan {
            get {
                return this.NamaRuanganField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaRuanganField, value) != true)) {
                    this.NamaRuanganField = value;
                    this.RaisePropertyChanged("NamaRuangan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TglKeluar {
            get {
                return this.TglKeluarField;
            }
            set {
                if ((object.ReferenceEquals(this.TglKeluarField, value) != true)) {
                    this.TglKeluarField = value;
                    this.RaisePropertyChanged("TglKeluar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TglMasuk {
            get {
                return this.TglMasukField;
            }
            set {
                if ((object.ReferenceEquals(this.TglMasukField, value) != true)) {
                    this.TglMasukField = value;
                    this.RaisePropertyChanged("TglMasuk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahRJ", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahRJ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BiayaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeObatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodePasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeRJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaObatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TglPeriksaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Biaya {
            get {
                return this.BiayaField;
            }
            set {
                if ((object.ReferenceEquals(this.BiayaField, value) != true)) {
                    this.BiayaField = value;
                    this.RaisePropertyChanged("Biaya");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeDokter {
            get {
                return this.KodeDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeDokterField, value) != true)) {
                    this.KodeDokterField = value;
                    this.RaisePropertyChanged("KodeDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeObat {
            get {
                return this.KodeObatField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeObatField, value) != true)) {
                    this.KodeObatField = value;
                    this.RaisePropertyChanged("KodeObat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodePasien {
            get {
                return this.KodePasienField;
            }
            set {
                if ((object.ReferenceEquals(this.KodePasienField, value) != true)) {
                    this.KodePasienField = value;
                    this.RaisePropertyChanged("KodePasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeRJ {
            get {
                return this.KodeRJField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeRJField, value) != true)) {
                    this.KodeRJField = value;
                    this.RaisePropertyChanged("KodeRJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaDokter {
            get {
                return this.NamaDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaDokterField, value) != true)) {
                    this.NamaDokterField = value;
                    this.RaisePropertyChanged("NamaDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaObat {
            get {
                return this.NamaObatField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaObatField, value) != true)) {
                    this.NamaObatField = value;
                    this.RaisePropertyChanged("NamaObat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaPasien {
            get {
                return this.NamaPasienField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaPasienField, value) != true)) {
                    this.NamaPasienField = value;
                    this.RaisePropertyChanged("NamaPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TglPeriksa {
            get {
                return this.TglPeriksaField;
            }
            set {
                if ((object.ReferenceEquals(this.TglPeriksaField, value) != true)) {
                    this.TglPeriksaField = value;
                    this.RaisePropertyChanged("TglPeriksa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahRuangan", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahRuangan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeRuanganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaRuanganField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeRuangan {
            get {
                return this.KodeRuanganField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeRuanganField, value) != true)) {
                    this.KodeRuanganField = value;
                    this.RaisePropertyChanged("KodeRuangan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaRuangan {
            get {
                return this.NamaRuanganField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaRuanganField, value) != true)) {
                    this.NamaRuanganField = value;
                    this.RaisePropertyChanged("NamaRuangan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahObat", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahObat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeObatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaObatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeObat {
            get {
                return this.KodeObatField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeObatField, value) != true)) {
                    this.KodeObatField = value;
                    this.RaisePropertyChanged("KodeObat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaObat {
            get {
                return this.NamaObatField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaObatField, value) != true)) {
                    this.NamaObatField = value;
                    this.RaisePropertyChanged("NamaObat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahPemeriksaan", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahPemeriksaan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnosaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HasilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodePasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodePemeriksaanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TglPeriksaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnosa {
            get {
                return this.DiagnosaField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnosaField, value) != true)) {
                    this.DiagnosaField = value;
                    this.RaisePropertyChanged("Diagnosa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hasil {
            get {
                return this.HasilField;
            }
            set {
                if ((object.ReferenceEquals(this.HasilField, value) != true)) {
                    this.HasilField = value;
                    this.RaisePropertyChanged("Hasil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeDokter {
            get {
                return this.KodeDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeDokterField, value) != true)) {
                    this.KodeDokterField = value;
                    this.RaisePropertyChanged("KodeDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodePasien {
            get {
                return this.KodePasienField;
            }
            set {
                if ((object.ReferenceEquals(this.KodePasienField, value) != true)) {
                    this.KodePasienField = value;
                    this.RaisePropertyChanged("KodePasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodePemeriksaan {
            get {
                return this.KodePemeriksaanField;
            }
            set {
                if ((object.ReferenceEquals(this.KodePemeriksaanField, value) != true)) {
                    this.KodePemeriksaanField = value;
                    this.RaisePropertyChanged("KodePemeriksaan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaDokter {
            get {
                return this.NamaDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaDokterField, value) != true)) {
                    this.NamaDokterField = value;
                    this.RaisePropertyChanged("NamaDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaPasien {
            get {
                return this.NamaPasienField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaPasienField, value) != true)) {
                    this.NamaPasienField = value;
                    this.RaisePropertyChanged("NamaPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TglPeriksa {
            get {
                return this.TglPeriksaField;
            }
            set {
                if ((object.ReferenceEquals(this.TglPeriksaField, value) != true)) {
                    this.TglPeriksaField = value;
                    this.RaisePropertyChanged("TglPeriksa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahLoginKaryawan", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahLoginKaryawan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeKaryawanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaKaryawanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeKaryawan {
            get {
                return this.KodeKaryawanField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeKaryawanField, value) != true)) {
                    this.KodeKaryawanField = value;
                    this.RaisePropertyChanged("KodeKaryawan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaKaryawan {
            get {
                return this.NamaKaryawanField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaKaryawanField, value) != true)) {
                    this.NamaKaryawanField = value;
                    this.RaisePropertyChanged("NamaKaryawan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahLoginDokter", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahLoginDokter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaDokterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeDokter {
            get {
                return this.KodeDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeDokterField, value) != true)) {
                    this.KodeDokterField = value;
                    this.RaisePropertyChanged("KodeDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaDokter {
            get {
                return this.NamaDokterField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaDokterField, value) != true)) {
                    this.NamaDokterField = value;
                    this.RaisePropertyChanged("NamaDokter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahLoginApoteker", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class TambahLoginApoteker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeApotekerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaApotekerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeApoteker {
            get {
                return this.KodeApotekerField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeApotekerField, value) != true)) {
                    this.KodeApotekerField = value;
                    this.RaisePropertyChanged("KodeApoteker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaApoteker {
            get {
                return this.NamaApotekerField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaApotekerField, value) != true)) {
                    this.NamaApotekerField = value;
                    this.RaisePropertyChanged("NamaApoteker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassLogin", Namespace="http://schemas.datacontract.org/2004/07/ServiceRS")]
    [System.SerializableAttribute()]
    public partial class ClassLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtKaryawan", ReplyAction="http://tempuri.org/IService1/TambahDtKaryawanResponse")]
        string TambahDtKaryawan(ProjectAkhir.ServiceReference1.TambahKaryawan DataKaryawan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtKaryawan", ReplyAction="http://tempuri.org/IService1/TambahDtKaryawanResponse")]
        System.Threading.Tasks.Task<string> TambahDtKaryawanAsync(ProjectAkhir.ServiceReference1.TambahKaryawan DataKaryawan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtApoteker", ReplyAction="http://tempuri.org/IService1/TambahDtApotekerResponse")]
        string TambahDtApoteker(ProjectAkhir.ServiceReference1.TambahApoteker DataApoteker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtApoteker", ReplyAction="http://tempuri.org/IService1/TambahDtApotekerResponse")]
        System.Threading.Tasks.Task<string> TambahDtApotekerAsync(ProjectAkhir.ServiceReference1.TambahApoteker DataApoteker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtDokter", ReplyAction="http://tempuri.org/IService1/TambahDtDokterResponse")]
        string TambahDtDokter(ProjectAkhir.ServiceReference1.TambahDokter DataDokter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtDokter", ReplyAction="http://tempuri.org/IService1/TambahDtDokterResponse")]
        System.Threading.Tasks.Task<string> TambahDtDokterAsync(ProjectAkhir.ServiceReference1.TambahDokter DataDokter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtPerawat", ReplyAction="http://tempuri.org/IService1/TambahDtPerawatResponse")]
        string TambahDtPerawat(ProjectAkhir.ServiceReference1.TambahPerawat DataPerawat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtPerawat", ReplyAction="http://tempuri.org/IService1/TambahDtPerawatResponse")]
        System.Threading.Tasks.Task<string> TambahDtPerawatAsync(ProjectAkhir.ServiceReference1.TambahPerawat DataPerawat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtPasien", ReplyAction="http://tempuri.org/IService1/TambahDtPasienResponse")]
        string TambahDtPasien(ProjectAkhir.ServiceReference1.TambahPasien DataPasien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtPasien", ReplyAction="http://tempuri.org/IService1/TambahDtPasienResponse")]
        System.Threading.Tasks.Task<string> TambahDtPasienAsync(ProjectAkhir.ServiceReference1.TambahPasien DataPasien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtRawatInap", ReplyAction="http://tempuri.org/IService1/TambahDtRawatInapResponse")]
        string TambahDtRawatInap(ProjectAkhir.ServiceReference1.TambahRI DataRawatInap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtRawatInap", ReplyAction="http://tempuri.org/IService1/TambahDtRawatInapResponse")]
        System.Threading.Tasks.Task<string> TambahDtRawatInapAsync(ProjectAkhir.ServiceReference1.TambahRI DataRawatInap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtRawatJalan", ReplyAction="http://tempuri.org/IService1/TambahDtRawatJalanResponse")]
        string TambahDtRawatJalan(ProjectAkhir.ServiceReference1.TambahRJ DataRawatJalan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtRawatJalan", ReplyAction="http://tempuri.org/IService1/TambahDtRawatJalanResponse")]
        System.Threading.Tasks.Task<string> TambahDtRawatJalanAsync(ProjectAkhir.ServiceReference1.TambahRJ DataRawatJalan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtRuangan", ReplyAction="http://tempuri.org/IService1/TambahDtRuanganResponse")]
        string TambahDtRuangan(ProjectAkhir.ServiceReference1.TambahRuangan DataRuangan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtRuangan", ReplyAction="http://tempuri.org/IService1/TambahDtRuanganResponse")]
        System.Threading.Tasks.Task<string> TambahDtRuanganAsync(ProjectAkhir.ServiceReference1.TambahRuangan DataRuangan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtObat", ReplyAction="http://tempuri.org/IService1/TambahDtObatResponse")]
        string TambahDtObat(ProjectAkhir.ServiceReference1.TambahObat DataObat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtObat", ReplyAction="http://tempuri.org/IService1/TambahDtObatResponse")]
        System.Threading.Tasks.Task<string> TambahDtObatAsync(ProjectAkhir.ServiceReference1.TambahObat DataObat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtPemeriksaan", ReplyAction="http://tempuri.org/IService1/TambahDtPemeriksaanResponse")]
        string TambahDtPemeriksaan(ProjectAkhir.ServiceReference1.TambahPemeriksaan DataPemeriksaan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahDtPemeriksaan", ReplyAction="http://tempuri.org/IService1/TambahDtPemeriksaanResponse")]
        System.Threading.Tasks.Task<string> TambahDtPemeriksaanAsync(ProjectAkhir.ServiceReference1.TambahPemeriksaan DataPemeriksaan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahLK", ReplyAction="http://tempuri.org/IService1/TambahLKResponse")]
        string TambahLK(ProjectAkhir.ServiceReference1.TambahLoginKaryawan LoginKaryawan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahLK", ReplyAction="http://tempuri.org/IService1/TambahLKResponse")]
        System.Threading.Tasks.Task<string> TambahLKAsync(ProjectAkhir.ServiceReference1.TambahLoginKaryawan LoginKaryawan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahLD", ReplyAction="http://tempuri.org/IService1/TambahLDResponse")]
        string TambahLD(ProjectAkhir.ServiceReference1.TambahLoginDokter LoginDokter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahLD", ReplyAction="http://tempuri.org/IService1/TambahLDResponse")]
        System.Threading.Tasks.Task<string> TambahLDAsync(ProjectAkhir.ServiceReference1.TambahLoginDokter LoginDokter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahLA", ReplyAction="http://tempuri.org/IService1/TambahLAResponse")]
        string TambahLA(ProjectAkhir.ServiceReference1.TambahLoginApoteker LoginApoteker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TambahLA", ReplyAction="http://tempuri.org/IService1/TambahLAResponse")]
        System.Threading.Tasks.Task<string> TambahLAAsync(ProjectAkhir.ServiceReference1.TambahLoginApoteker LoginApoteker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataLogin", ReplyAction="http://tempuri.org/IService1/GetDataLoginResponse")]
        ProjectAkhir.ServiceReference1.ClassLogin GetDataLogin(ProjectAkhir.ServiceReference1.ClassLogin CL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataLogin", ReplyAction="http://tempuri.org/IService1/GetDataLoginResponse")]
        System.Threading.Tasks.Task<ProjectAkhir.ServiceReference1.ClassLogin> GetDataLoginAsync(ProjectAkhir.ServiceReference1.ClassLogin CL);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProjectAkhir.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProjectAkhir.ServiceReference1.IService1>, ProjectAkhir.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TambahDtKaryawan(ProjectAkhir.ServiceReference1.TambahKaryawan DataKaryawan) {
            return base.Channel.TambahDtKaryawan(DataKaryawan);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtKaryawanAsync(ProjectAkhir.ServiceReference1.TambahKaryawan DataKaryawan) {
            return base.Channel.TambahDtKaryawanAsync(DataKaryawan);
        }
        
        public string TambahDtApoteker(ProjectAkhir.ServiceReference1.TambahApoteker DataApoteker) {
            return base.Channel.TambahDtApoteker(DataApoteker);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtApotekerAsync(ProjectAkhir.ServiceReference1.TambahApoteker DataApoteker) {
            return base.Channel.TambahDtApotekerAsync(DataApoteker);
        }
        
        public string TambahDtDokter(ProjectAkhir.ServiceReference1.TambahDokter DataDokter) {
            return base.Channel.TambahDtDokter(DataDokter);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtDokterAsync(ProjectAkhir.ServiceReference1.TambahDokter DataDokter) {
            return base.Channel.TambahDtDokterAsync(DataDokter);
        }
        
        public string TambahDtPerawat(ProjectAkhir.ServiceReference1.TambahPerawat DataPerawat) {
            return base.Channel.TambahDtPerawat(DataPerawat);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtPerawatAsync(ProjectAkhir.ServiceReference1.TambahPerawat DataPerawat) {
            return base.Channel.TambahDtPerawatAsync(DataPerawat);
        }
        
        public string TambahDtPasien(ProjectAkhir.ServiceReference1.TambahPasien DataPasien) {
            return base.Channel.TambahDtPasien(DataPasien);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtPasienAsync(ProjectAkhir.ServiceReference1.TambahPasien DataPasien) {
            return base.Channel.TambahDtPasienAsync(DataPasien);
        }
        
        public string TambahDtRawatInap(ProjectAkhir.ServiceReference1.TambahRI DataRawatInap) {
            return base.Channel.TambahDtRawatInap(DataRawatInap);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtRawatInapAsync(ProjectAkhir.ServiceReference1.TambahRI DataRawatInap) {
            return base.Channel.TambahDtRawatInapAsync(DataRawatInap);
        }
        
        public string TambahDtRawatJalan(ProjectAkhir.ServiceReference1.TambahRJ DataRawatJalan) {
            return base.Channel.TambahDtRawatJalan(DataRawatJalan);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtRawatJalanAsync(ProjectAkhir.ServiceReference1.TambahRJ DataRawatJalan) {
            return base.Channel.TambahDtRawatJalanAsync(DataRawatJalan);
        }
        
        public string TambahDtRuangan(ProjectAkhir.ServiceReference1.TambahRuangan DataRuangan) {
            return base.Channel.TambahDtRuangan(DataRuangan);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtRuanganAsync(ProjectAkhir.ServiceReference1.TambahRuangan DataRuangan) {
            return base.Channel.TambahDtRuanganAsync(DataRuangan);
        }
        
        public string TambahDtObat(ProjectAkhir.ServiceReference1.TambahObat DataObat) {
            return base.Channel.TambahDtObat(DataObat);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtObatAsync(ProjectAkhir.ServiceReference1.TambahObat DataObat) {
            return base.Channel.TambahDtObatAsync(DataObat);
        }
        
        public string TambahDtPemeriksaan(ProjectAkhir.ServiceReference1.TambahPemeriksaan DataPemeriksaan) {
            return base.Channel.TambahDtPemeriksaan(DataPemeriksaan);
        }
        
        public System.Threading.Tasks.Task<string> TambahDtPemeriksaanAsync(ProjectAkhir.ServiceReference1.TambahPemeriksaan DataPemeriksaan) {
            return base.Channel.TambahDtPemeriksaanAsync(DataPemeriksaan);
        }
        
        public string TambahLK(ProjectAkhir.ServiceReference1.TambahLoginKaryawan LoginKaryawan) {
            return base.Channel.TambahLK(LoginKaryawan);
        }
        
        public System.Threading.Tasks.Task<string> TambahLKAsync(ProjectAkhir.ServiceReference1.TambahLoginKaryawan LoginKaryawan) {
            return base.Channel.TambahLKAsync(LoginKaryawan);
        }
        
        public string TambahLD(ProjectAkhir.ServiceReference1.TambahLoginDokter LoginDokter) {
            return base.Channel.TambahLD(LoginDokter);
        }
        
        public System.Threading.Tasks.Task<string> TambahLDAsync(ProjectAkhir.ServiceReference1.TambahLoginDokter LoginDokter) {
            return base.Channel.TambahLDAsync(LoginDokter);
        }
        
        public string TambahLA(ProjectAkhir.ServiceReference1.TambahLoginApoteker LoginApoteker) {
            return base.Channel.TambahLA(LoginApoteker);
        }
        
        public System.Threading.Tasks.Task<string> TambahLAAsync(ProjectAkhir.ServiceReference1.TambahLoginApoteker LoginApoteker) {
            return base.Channel.TambahLAAsync(LoginApoteker);
        }
        
        public ProjectAkhir.ServiceReference1.ClassLogin GetDataLogin(ProjectAkhir.ServiceReference1.ClassLogin CL) {
            return base.Channel.GetDataLogin(CL);
        }
        
        public System.Threading.Tasks.Task<ProjectAkhir.ServiceReference1.ClassLogin> GetDataLoginAsync(ProjectAkhir.ServiceReference1.ClassLogin CL) {
            return base.Channel.GetDataLoginAsync(CL);
        }
    }
}
